---
title: "species_plantnet"
author: "Paula Uzcategui"
date: "2026-02-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Merge Panama Biota BCI list and Panama woody plant list to create a BCI woody species list

```{r setup2, echo=TRUE,message=FALSE, warning=FALSE, results="hide"}

rm(list=ls())

library("readxl")
library("writexl")
library("dplyr")
library(tidyr)
library("stringi")
library("stringr")
library(DT)
```

# Preparing the datasets

```{r prep, echo=TRUE, results="hide"}

save_plantlists_dir = "splists_out/Plantnet species/"

pbiota_list <- read_excel("splists_out/PanamaBiotaBCI_WCVP_2026-02-22.xlsx")
woody_list <- read_excel("splists_out/CurrentPanamaWoody_2026-02-22.xlsx")
lianas_list <- read_excel("splists_out/Lianas_Species_complete_list_2026-02-13_WCVP_2026-02-22.xlsx")
garwood_list <- read_excel("splists_out/Garwood_2009_Appendix1_WCVP_2026-02-20.xlsx")
zotz_list <- read_excel("splists_out/83_Zotz_Epiphytes_TableS1_WCVP_2026-02-22.xlsx")

woody_synonyms <- read_excel("splists_out/CurrentPanamaWoody_SYNONYMS_2026-02-22.xlsx")
garwood_synonyms <- read_excel("splists_raw/Garwood/Garwood_2009_Appendix1_Synonyms.xlsx") 


garwood_synonyms <- garwood_synonyms %>% mutate(
  sp_name = trimws(paste0(Genus, " ", Species)),
  synonym_sp = trimws(paste0(SynonymGenusSingle, " ", SynonymSpeciesSingle)))

```
## BCI LIST

### Zotz list
```{r zotzlist, echo=TRUE, results="hide"}

# 1. see match by origin name
match_orig <- match(zotz_list$orig_name, garwood_list$orig_name)
zotz_no_orig <- zotz_list %>% filter(is.na(match_orig))

# 2. see match by wcvp names
match_wcvp <- match(zotz_no_orig$current_name, garwood_list$current_name)
zotz_no_wcvp <- zotz_no_orig %>% filter(is.na(match_wcvp))

# 3. add a filed for synonym presence
zotz_no_wcvp <- zotz_no_wcvp %>%
  mutate(is_garwood_synonym = orig_name %in% garwood_synonyms$synonym_sp | current_name %in% garwood_synonyms$synonym_sp)

```

Add to bci list
```{r}
# using garwood as a base
garwood_list$source_list = "Garwood2009"
zotz_no_wcvp$source_list = "Zotz"

listscol <- c("current_family", "current_name", "orig_family", "orig_name","current_author", "orig_author","Name_matched", "wcvp_status", "wcvp_lifeform_description", "current_name_notes", "source_list")

bcilist <- bind_rows(
  garwood_list %>% 
    select(listscol, SYNONYMS),
  zotz_no_wcvp %>% select(listscol, is_garwood_synonym)
)

```


### Panama biota list
```{r panamabiotabcilist, echo=TRUE, results="hide"}

# 1. see match by origin name
match_orig <- match(pbiota_list$orig_name, bcilist$orig_name)
pbiota_no_orig <- pbiota_list %>% filter(is.na(match_orig))

# 2. see match by wcvp names
match_wcvp <- match(pbiota_no_orig$current_name, bcilist$current_name)
pbiota_no_wcvp <- pbiota_no_orig %>% filter(is.na(match_wcvp))


# 3. add field for synonym presence
pbiota_no_wcvp <- pbiota_no_wcvp %>%
  mutate(is_garwood_synonym = orig_name %in% garwood_synonyms$synonym_sp | current_name %in%  garwood_synonyms$synonym_sp )

```

Add to bci list
```{r mergebci}

pbiota_no_wcvp$source_list = "PanamaBiota"
pbiota_no_wcvp <- pbiota_no_wcvp %>% select(listscol, is_garwood_synonym)

bcilist <- bind_rows(bcilist, pbiota_no_wcvp)


# remove NA and a error in a row
bcilist <- bcilist %>% filter(!is.na(current_name) & current_name !="Not categorized as epiphytes any more:")

bcilist <- bcilist %>% mutate(
  zotz = current_name %in% zotz_list$current_name | orig_name %in% zotz_list$orig_name,
  garwood =  current_name %in% garwood_list$current_name | orig_name %in% garwood_list$orig_name,
  panamabiota = current_name %in% pbiota_list$current_name | orig_name %in% pbiota_list$orig_name,
)

bcilist<- bcilist %>%
  left_join(
    garwood_synonyms %>% select(sp_orig = sp_name, synonym_sp, syn_orig = SynonymTextALL) %>% distinct(),
    by = c("orig_name" = "synonym_sp")
  ) %>%
  left_join(
    garwood_synonyms %>% select(sp_curr = sp_name, synonym_sp, syn_curr = SynonymTextALL) %>% distinct(),
    by = c("current_name" = "synonym_sp"), relationship = "many-to-many") %>%
  mutate(
    SynonymTextALL = coalesce(syn_orig, syn_curr),
    orig_garwood = coalesce(sp_orig, sp_curr)
  ) %>%
  select(-syn_orig, -syn_curr, -sp_orig, -sp_curr) %>%
  distinct(current_name, orig_name, .keep_all = TRUE)
 

datatable(
  bcilist %>% filter(is_garwood_synonym == TRUE) %>%
    select(current_name, orig_name, source_list,orig_garwood, SynonymTextALL) %>% 
    arrange(source_list),
    caption="Species in zotz or panamabiota that are in garwood as synonyms only",
  options = list(scrollX = TRUE, pageLength = 10))

datatable(
  bcilist %>% filter(!garwood & panamabiota & zotz) %>%
    select(current_name, orig_name, source_list,zotz, garwood, panamabiota, is_garwood_synonym,orig_garwood, SynonymTextALL ) %>% 
    arrange(source_list),
    caption="Species that are in zotz and panama biota but not in garwood",
  options = list(scrollX = TRUE, pageLength = 10),
  )

```

```{r printresult}

datatable(
  bcilist %>%
    select(current_name, orig_name, source_list,zotz, garwood, panamabiota) %>% 
    arrange(source_list),
    caption="Species list in BCI and their source",
  options = list(scrollX = TRUE, pageLength = 10))

```

```{r bcilistwoody, echo=TRUE, results="hide"}
# set woody if:
# current name is in woody list 
# current name is in woody synonym list

bcilist <- bcilist %>% mutate(
  woody_name = current_name %in% woody_list$current_name,
  woody_synonym =  current_name %in% woody_synonyms$SynonymTextSingle 
                  | orig_name %in% woody_synonyms$SynonymTextSingle, 
  woody = woody_name | woody_synonym
) 

write_xlsx(bcilist, paste0(save_plantlists_dir, "BCI_SPECIES_LIST_",Sys.Date(),".xlsx"))


```

# Woody species

```{r woodylist, results="hide", echo=TRUE}

# Woody species

forestgeo_regional_list <- read_excel("splists_raw/Forestgeo/2025-12-04FromSuzanne/ViewTaxonomy_dec4_25.xlsx")

# Column of forestgeo regional list
sum(is.na(forestgeo_regional_list$Mnemonic))

match12 <- match(woody_list$sp6, forestgeo_regional_list$Mnemonic)            

woody_list[is.na(match12),] %>% select(sp6, current_name , forestgeo_name)

match21 <- match(forestgeo_regional_list$Mnemonic, woody_list$sp6)            

nomatchview <- forestgeo_regional_list[is.na(match21),] %>% select(Mnemonic, SpeciesName)
#almost everything that didint match is unidentified
#nomatchview$SpeciesName


### add column if its in the plots
abundall <- read_excel("splists_raw/Plots/abundance_plots_HM.xlsx")

abundall <- abundall %>% select(sp, binomial, bci, `bci 10 ha plot`,P14, P11)%>% 
                      filter( bci >0 | `bci 10 ha plot` > 0 | P14 > 0| P11 >0)

match21 <- match(abundall$sp, woody_list$sp6)            
nomatchview <- abundall[is.na(match21),] %>% select(sp, binomial)

plotbci_list <- abundall %>% filter(bci >0)
plotbci10ha_list <- abundall %>% filter(`bci 10 ha plot`  >0)
plotp14_list <- abundall %>% filter(P14 >0)
plotp11_list <- abundall %>% filter(P11 >0)


### Add columns ####

woody_synonyms_bci <-  woody_synonyms %>%
  mutate(syn_bci_name = SynonymTextSingle %in% bcilist$current_name | SynonymTextSingle %in% bcilist$orig_name) %>%
  filter(syn_bci_name) %>% 
  pull(current_name)

woody_list <- woody_list %>% mutate(
  forestgeo_regional = sp6 %in% forestgeo_regional_list$Mnemonic,
  plotbci = sp6 %in% plotbci_list$sp,
  plotbci10 = sp6 %in% plotbci10ha_list$sp,
  plotp14 = sp6 %in% plotp14_list$sp,
  plotp11 = sp6 %in% plotp11_list$sp,
  syn_bci_name = current_name %in% woody_synonyms_bci,
  bci_name = current_name %in% bcilist$current_name,
  bci_list = bci_name | syn_bci_name,
  bci =  bci_name | syn_bci_name | plotbci | plotbci10 | plotp14 | plotp11
)

#################### save new woody species list: 

write_xlsx(woody_list, paste0(save_plantlists_dir, "WOODY_SPECIES_",Sys.Date(),".xlsx"))

# sanity check

woodybci <- woody_list %>% filter(bci_list)
bciwoody <- bcilist %>% filter(woody)
match12 <- match(bciwoody$current_name, woodybci$current_name)
datatable(bciwoody %>% filter(is.na(match12)) %>% select(current_name, orig_name, source_list, current_name_notes),
          caption="Species where current name appears only as a synonym of a woody species",
          options = list(scrollX = TRUE, pageLength = 10))

```



### Woody species that are NOT in garwood, zotz or panama biota but they are in BCI plots

```{r sanitycheck_bci, fig.width=10}

# How do we verify that no species is being missed?

# print species NOT in panama biota but they are in the plots
plotmatch <- woody_list %>% filter(!bci_list & bci) %>% select(current_name, forestgeo_name, forestgeo_synonyms, plotbci, plotbci10, plotp11, plotp11)


knitr::kable(plotmatch, caption="Woody species dont match with the bci lists (garwood, zotz, panamabiota) but have been reported in bci plots")


```

